### ISSUE TITLE
Response from create Connect Webview does not include set customMetadata.

### ISSUE THREAD

**Issue by DebbieAtSeam** [seamapi/csharp#15]
In this code, the output form the last line does not include the set customMetadata, but if I get the same object using the HTTP API, it _does_ show the set customMetadata. Is this the correct behavior, or should the create response include the set customMetadata?

```
var userId = "user1";
var customMetadata = new Dictionary<string, string>()
{
  {"id", userId}
};

var createdConnectWebview = seam.ConnectWebviews.Create(
  providerCategory: Seam.Api.ConnectWebviews.CreateRequest.ProviderCategoryEnum.Stable,
  customMetadata: customMetadata
);

Console.WriteLine(createdConnectWebview);
```

**Comment by mxsdev** [comment]
@DebbieAtSeam 

Can you provide the result of `Console.WriteLine(createdConnectWebview)`?

**Comment by DebbieAtSeam** [comment]
@mxsdev: Just tried it, and now it shows the custom metadata!

**Comment by DebbieAtSeam** [comment]
I'm sorry if I just missed it before!
